### PR TITLE
Nextcloud 11 Compatibility

### PR DESCRIPTION
**Pull request by 4oo4**
Not sure if this is still being actively developed, but I came up with this when I realized it wasn't working in Nextcloud 11. I believe they changed something with the Content Security Policy, and this meant that the Notes app and list of notes would load, but a CSP would prevent the note itself from loading when clicked.

There's probably a more precise way of doing this, I still get a console error in Chromium that the CSP doesn't like that there's not a nonce or hash:
```
tinymce.min.js?v=171c1ff…:2370 Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'nonce-QmJuNWMwcjlTbng5cXIzSWRlT2VnUWd2SmxyWXViVFphN2xWSTBjSHdkST06TjhuT0pRS3RDQXNzeGVtbUVLdjc3WGw0UWpDSzZJZTJMdUU4UURSc2pvVT0=' * 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

(anonymous) @ tinymce.min.js?v=171c1ff…:2370
run @ tinymce.min.js?v=171c1ff…:2573
add @ tinymce.min.js?v=171c1ff…:2368
init @ tinymce.min.js?v=171c1ff…:8515
(anonymous) @ tinymce.min.js?v=171c1ff…:8439
(anonymous) @ tinymce.min.js?v=171c1ff…:2776
a @ tinymce.min.js?v=171c1ff…:1024
h @ tinymce.min.js?v=171c1ff…:2775
(anonymous) @ tinymce.min.js?v=171c1ff…:2773
i @ tinymce.min.js?v=171c1ff…:2726
```
This at least gets the app working again as far as I can tell, there may be something that's held back because of this additional CSP error.

Is someone able to point me how to use NC/OC's existing nonce policies for CSP for a permanent fix? I was looking here but not getting very far:

https://github.com/owncloud/core/pull/13989
https://central.owncloud.org/t/how-to-correctly-set-csp/2446/4
https://github.com/nextcloud/server/blob/e1b806467c19f85af975fcbc9793a730614c2963/lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php
https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/Security/CSP/ContentSecurityPolicy.php
https://statuscode.ch/2015/04/content-security-policy-and-ownCloud/

### CODE REVIEW

**Comment by 4oo4** [comment]
Ahh, just saw #335 , that's looking like a much better solution

**Comment by 4oo4** [comment]
My master branch has some fixes that others have proposed that totally fix the compatibility issues (this first attempt was too hack-y. If there's any interest I can resubmit that one. Thanks to everyone that put forward solutions!

**Comment by Fmstrat** [comment]
Mind if I just make you an admin on this repo?

**Comment by enoch85** [comment]
ping @4oo4 Would you like to be admin for this repo and maintain it?

**Comment by Fmstrat** [comment]
@4oo4 just piling on with @enoch85. Your branch looks good, would be happy to add you as an admin if you're interested.

**Pull request closed without merging**
