### PR TITLE
Update info.xml

### PR DESCRIPTION
**Pull request by joergmschulz**
add installability for recent nextcloud versions

### CODE REVIEW

**Comment by enoch85** [comment]
@Fmstrat Hey,could you get this in? Also please fix the versions in the future so that everyone with Nextcloud can use this app. Thanks!

Current version is 11 btw. Maybe it should say 1 instead @joergmschulz ?

**Comment by joergmschulz** [comment]
I don't understand the '1' bit? What would you change@which place?

**Comment by enoch85** [comment]
@joergmschulz Sorry, meant 12.

**Comment by joergmschulz** [comment]
let's stick to eleven - we didn't even test ownNote on 11 thoroughly (does anybody know whether the packet is maintained anyway?)

**Comment by enoch85** [comment]
I run ownNote successfully on Nextcloud 11. 

Don't know if it's maintained. Seems not like it I'm afraid. :/

**Comment by Fmstrat** [comment]
It's maintained, just not frequently unfortunately. My full time job has me traveling a lot, so I don't get a lot of time to improve on this project. That being said, having it "work" is a big deal, so I'll get this merged in once I get a chance to test formally, likely this weekend but maybe before.

**Comment by jancborchardt** [comment]
@Fmstrat just saying, that is why it would be cool to collaborate one one great app like [Nextcloud Notes](https://github.com/nextcloud/notes) :) Then there’s no bottlenecks, nice working together, and the users get a great maintained app.

cc @Henni @korelstar of the app. With the switch to a new editor there’s the [ability for formatting (beyond markdown)](https://github.com/nextcloud/notes/pull/22), [grouping/categorization is being worked on](https://github.com/nextcloud/notes/pull/6), and pasting images might also be something worth exploring. @Henni and I also talked about the possibility of [sharing a single note](https://github.com/nextcloud/notes/issues/38).
All while keeping a simple UI of course. It would be great if we could collaborate on one great app. Import from Evernote,Simplenote and others would be massively useful for example. What do you think @Fmstrat?

**Comment by enoch85** [comment]
@jancborchardt Great idea! Is it this app you're talking about? https://apps.nextcloud.com/apps/nextnotes

And what about the mobile client?

**Comment by korelstar** [comment]
@enoch85 
No, it's https://apps.nextcloud.com/apps/notes (unfortunately, a good description is still missing).

Nextcloud Notes have a nice mobile client, too. It's open source (https://github.com/stefan-niedermann/OwnCloud-Notes) and on [Google Play](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes) and [F-Droid](https://f-droid.org/repository/browse/?fdid=it.niedermann.owncloud.notes).

**Comment by enoch85** [comment]
@Next Notes looks more like this app, with picture upload and other neat stuff (at least from the screenshot) whilst the Notes app is more like a Markdown notes app. Personally I'd prefer something like Next Note/ownNote with a nice Notes app clean design.

Would that be possible? As @Fmstrat doesn't have that much time on his hands... :/

**Comment by jancborchardt** [comment]
@enoch85 I was talking to @Henni of Nextcloud Notes and he talked with the Nextnotes developer @janis91 already and they will collaborate.

It is really important that we as a small open source community make sure to collaborate, especially on something as essential as a Notes app, and make it as great as possible. Having single people develop on an app leads to unmaintained apps in the long run, and unhappy users. Or do I need to remind you about the »Plus«-apps? ;)

We need to build a strong team for each app, help each other out, and focus our attention. Then we also have the resources to build advanced features properly rather than just throw them in.

Lastly, for me and even the whole @nextcloud/designers team it would be very difficult to spread over multiple apps of the exact same type and make sure they all look & work nicely as people expect from Nextcloud.

**Comment by enoch85** [comment]
@jancborchardt 

> do I need to remind you about the »Plus«-apps? ;)

Oh no, don't remind me, I had forgotten. 

**I totally agree** that we should try to organize instead of everyone developing in their own corners. One of the worst scenarios is when an app which is great and with great potential isn't maintained due to the reasons you mentioned. 

Just as a side note, the Documents app  (not e *great* app, but used by many)  is such an example, but we already discussed that ;)

**Comment by enoch85** [comment]
Any news here @Fmstrat?

**Comment by enoch85** [comment]
@Fmstrat echo :)

**Comment by enoch85** [comment]
I just tested, this fix works with 12 as well. Just change to 12 instead of 11.

@Fmstrat Please merge this once the version number is changed.

**Comment by enoch85** [comment]
Please join the work in https://github.com/brantje/ownnote/

**Comment by enoch85** [comment]
Merging this as it's valid

**Pull request merged**
