### PR TITLE
nextcloud csp level 2 feature implemented

### PR DESCRIPTION
**Pull request by q4z1**
this will work for the new nextcloud version only.
For ownCloud there should propably be a clause implemented which checks if a nonce is used.
Feel free to contact me.

### CODE REVIEW

**Comment by ThomasDaheim** [comment]
Works like a charm!

**Comment by enoch85** [comment]
@Fmstrat Can we merge this?

**Comment by e-alfred** [comment]
This would be great if it could get merged because Ownnotes does not work with Chrome anymore due tro this issue.

**Comment by enoch85** [comment]
@fmstrat Please merge.

**Comment by jospoortvliet** [comment]
might be time to fork :(

**Comment by enoch85** [comment]
Yeah, please do, he's vanished again.

**Comment by ThomasDaheim** [comment]
So who is going to fork? I also have a pull request open (#346) from my branch. The changes from this one are included there as well - along with those from #341 .

I could create a fork and give write access to e.g. @q4z1 and others willing to keep ownnote up & running.

**Comment by enoch85** [comment]
@ThomasDaheim Someone with write access to the Nextcloud organisation. cc @jospoortvliet ?

**Comment by ThomasDaheim** [comment]
However wants to contribute is welcome :-)

**Comment by enoch85** [comment]
Here's a start: https://github.com/brantje/ownnote

**Comment by ThomasDaheim** [comment]
Great! Now I only need to figure out what pull requests from here have made it to there :-)

**Comment by enoch85** [comment]
@ThomasDaheim That fork will be the next NextNotes app. So it would be great if you could push your PRs to that repo. :+1:

**Comment by ThomasDaheim** [comment]
Have moved the discussion over there...

**Pull request merged**
