### PR TITLE
Fix L10N-error

### PR DESCRIPTION
**Pull request by tflidd**
Fixes https://github.com/Fmstrat/ownnote/issues/278

### CODE REVIEW

**Comment by tflidd** [comment]
@timscha : I just created this pull request. Can you test if it works for you?

**Comment by timscha** [comment]
@tflidd Great. Can confirm it works fine. Tested with OC 9.0.0, PHP 7.0 and nginx 1.9. :)

**Comment by mschoeler** [comment]
@tflidd: Works

**Comment by enoch85** [comment]
Saved my life. Thanks!

**Comment by enoch85** [comment]
@tflidd Don't know if it's releated?

```
Method OC_L10N_String::__toString() must return a string value at /var/www/owncloud/lib/private/l10n/l10n.php#84 
```

**Comment by tflidd** [comment]
@enoch85 Is this related to the ownnote app?

**Comment by enoch85** [comment]
@tflidd As I said, don't know, but as your fix changed the exact same thing in the app.php I think so.

**Comment by tflidd** [comment]
@enoch85 This is a bit different. Is this related to a special app? If not, I would report it to core.

**Comment by Fmstrat** [comment]
Thanks so much for contributing.

**Pull request merged**
