### PR TITLE
Updated tinymce and add folder only mode

### PR DESCRIPTION
**Pull request by ThomasDaheim**
Various updates / fixes in this branch:
- updated to tinymce 4.6.1
- enabled new editor features
- added prim.js support
- added a new mode "folder only" where notes are ONLY stored in the file
system

Things that could still be done:
- TESTING
- add an admin option to sync database from/to folder
- update android client accordingly (can only be done by Ben)

### CODE REVIEW

**Comment by ThomasDaheim** [comment]
Includes updates from #341 and #335 as well.

**Comment by enoch85** [comment]
Can we close this as it will be in the new fork?

**Comment by Fmstrat** [comment]
As a note, folder-only mode could break the mobile app.

**Comment by ThomasDaheim** [comment]
@Fmstrat : Editing the files locally and not running ownnote in Nextcloud also breaks the mobile app :-( Not sure what the mobile app does to get the list of notes? Is there any local storage involved? I have updated so that the getNotes function works in all three cases. But I still see strange behavior in the mobile app...

**Comment by Fmstrat** [comment]
I can't remember why, because it's been a while, but I remember running into issues using the files for pulling note information vs pulling from the DB. That was why I removed the folder-only mode. The mobile source will be going up soon when I back home for the Nextcloud team to take over. I'm sure they (or community members like yourself) will spot the rationale and potential work around pretty quick when the time comes.

**Comment by enoch85** [comment]
@ThomasDaheim Please check that the resolved conflicts are correct. Thanks!

**Comment by ThomasDaheim** [comment]
@enoch85 : Not sure if merging  js/tinymce/tinymce.min.js is a good idea... And since we anyways move to the branch I wouldn't want to focus efforts on this one. Would it be possible to undo the merge and I would revert my pull request afterwards?

**Comment by enoch85** [comment]
@ThomasDaheim You can do it with git. https://stackoverflow.com/questions/3639115/reverting-to-a-specific-commit-based-on-commit-id-with-git

**Comment by ThomasDaheim** [comment]
OK. Will close this commit and see how changes can be included in https://github.com/brantje/ownnote

**Pull request closed without merging**
